### PR TITLE
Upgrade to VS2017

### PR DESCRIPTION
**Pull request by cwe1ss**
Because...
a31139b25398b832122116c394ffe77e4f5b028dac0f519996e5e3a7647a3094
(and because I no longer have VS2015)

Things I've done:
* Upgrade to VS2017 with `dotnet migrate`
* Upgrade of test dependencies (xunit etc to latest non-preview versions)

build.ps1 succeeds for me but there's a lot of analyzer warnings. Also, I haven't touched any of the surrounding scripts for signing etc. So this should definitely be reviewed before a merge.

PS: No C# files have been harmed during this migration! 😄

### CODE REVIEW

**Comment by dnduffy** [comment]
Thank-you, I had started on this myself but put it on hold to focus on the current release so I'll try to get this reviewed and merged as soon as we ship the next stable.

**Comment by cijothomas** [comment]
This can be merged after 2.1.1 is out which is expected tomorrow. I'll try to get a build machine with vs 2017 pool.

**Comment by cijothomas** [comment]
2 things need to happend prior:
1 - merge conflict. Should be easy,just remove project.json and update csproj with correct version of dependencies.
2. Update https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/develop/dirs.proj to build csproj. Its now looking for project.json

**Comment by cijothomas** [comment]
https://github.com/Microsoft/ApplicationInsights-aspnetcore/pull/443
I made another one for VS 2017 update, as a few others things were needed as well to make it work. Closing this.
Thanks a lot for making this contribution!

**Pull request closed without merging**
