### PR TITLE
added specific ApplicationInsightsLoggerOptions to configure logging

### PR DESCRIPTION
**Pull request by funkycoding**
PR https://github.com/Microsoft/ApplicationInsights-aspnetcore/pull/483 (belongs to issue #393) was made to send `ExceptionTelemetry` when the exception parameter of `public void Log<TState>(LogLevel logLevel, EventId eventId, TState state, Exception exception, Func<TState, Exception, string> formatter)` is not null.

This introduced some side effects in, for example, entity framework core. They log an exception using ILogger and then re-throw the exception to be (possibly) handled by the consumer. If the consumer then also logs that exception, we get double entries. I understand that ApplicationInsights wants to track as much as possible with less work but this introduced some quirks.

This PR proposes to introduce a `ApplicationInsightsLoggerOptions` to allow for some customization. I've tried to leave the public surface intact as much as possible and it defaults to the way it currently works.

Secondly, i haven't changed the overloads in `ApplicationInsightsLoggerFactoryExtensions`, because i'm not 100% sure how you guys would like to see this 😄 

- [x] I ran all tests locally. [Following contributer's guide] (https://github.com/Microsoft/ApplicationInsights-aspnetcore/blob/develop/Readme.md)
- [x] CHANGELOG.md updated with one line description of the fix, and a link to the original issue.

For significant contributions please make sure you have completed the following items:

- [ ] Changes in public surface reviewed
- [ ] The PR will trigger build, unit test, and functional tests automatically. If your PR was submitted from a fork - mention one of committers to initiate the build for you.

### CODE REVIEW

**Comment by funkycoding** [comment]
@cijothomas ping :) Not sure if i had to include you in here...

**Comment by cijothomas** [comment]
@funkycoding Thanks a lot for your contribution! And apologies for not responding quickly to the issues in this repo.  We'll be more actively monitoring this repo going forward.

I am not sure whether you saw this https://github.com/Microsoft/ApplicationInsights-aspnetcore/pull/570/files, but this one also introduces the notion of ```ApplicationInsightsLoggerOptions``` . 
I am reviewing the other PR now, and will ask author for couple changes. Please wait till that is completed and make neccessary changes here, and we'll merge this one as well.

(If i dont hear from PR author's in couple days I'll try to merge both into a single one myself)

**Comment by funkycoding** [comment]
@cijothomas ok! I'll await the feedback (and occasionally look to see i can merge / implement feedback).

**Comment by cijothomas** [comment]
@funkycoding The other PR I mentioned is in now. Can you adjust yours to take that into account?
Also update chagelog.md as well!
Thanks!

**Comment by funkycoding** [comment]
@cijothomas I've merged latest develop into my (local) repo, but the test project doesn't seem to work now. Hang in there...

**Comment by funkycoding** [comment]
@cijothomas Everything builds locally. I'm able to run the `Microsoft.ApplicationInsights.AspNetCore.Tests` tests (although, only through cmd/powershell). I noticed that the build failed. What can i do?

**Comment by d3r3kk** [comment]
@funkycoding A transient error occurred in our build pipeline - we can simply queue a new build to sort it out. 
Simply close, and then re-open, this PR.

**Comment by d3r3kk** [comment]
Perhaps this isn't such a transient error. I'll see if I can sort it out sometime today. Apologies!

**Comment by cijothomas** [comment]
Thanks Derek for helping here.
The transient failures are not related to this PR, - So I am merging this. (thanks @funkycoding for your contribution)

**Pull request merged**
