### PR TITLE
bump version 2.8.0-beta3

### PR DESCRIPTION
**Pull request by TimothyMothra**
also updated DiagnosticSource to stay in sync with WebSDK https://github.com/microsoft/ApplicationInsights-dotnet-server/pull/1252

### CODE REVIEW

**Comment by TimothyMothra** [comment]
Test failed: 

MVC20.FuncTests.TelemetryModuleWorkingMvcTests.TestIfPerformanceCountersAreCollected [25ms]
  Error Message:
   System.IO.IOException : Failed to bind to address http://127.0.0.1:12226: address already in use.

**Comment by lmolkova** [comment]
@cijothomas  
Didn't we have some tests disabled waiting for DepednedncyCollector? Should we re-enable them?

**Comment by cijothomas** [comment]
@lmolkova Yes we need to reenable all ignored tests.
[Fact(Skip = "Re-Enable once DependencyTrackingModule is updated to latest DiagnosticSource.")]

**Comment by TimothyMothra** [comment]
@cijothomas, just to confirm...
Do you want to wait until the stable release of DiagnosticSource?

**Comment by lmolkova** [comment]
@TimothyMothra tests are ready to be enabled now and should pass. This is I believe prereq for beta3. Would you mind enabling them as  a part of this PR?

**Comment by TimothyMothra** [comment]
@lmolkova gladly. i'll take care of it right now :)

**Comment by cijothomas** [comment]
ready to merge

**Pull request merged**
